spring.application.name=task-manager-api
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/task-manager?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=vinay@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwtSecret=ReplaceThisWithAStrongSecretKey12345
app.jwtExpirationMs=86400000
server.port=8080